# fly.toml file generated for winter-butterfly-5480 on 2021-10-13T14:58:15+03:00

app = "winter-butterfly-5480"

kill_signal = "SIGTERM"
kill_timeout = 5

[deploy]
  release_command = "/app/bin/phxcrd eval Phxcrd.Release.migrate"

[env]

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
